name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install angular-cli-ghpages
        run: npm install -g angular-cli-ghpages

      - name: Build
        run: ng build --base-href https://danieljancar.dev

      - name: Deploy
        run: ngh --dir=dist/portfolio/

      - name: Cleanup
        if: always()
        run: rm -rf node_modules
