name: Release Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build -- --base-href https://danieljancar.dev

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install and Build
        run: |
          npm ci
          npm run build -- --base-href https://danieljancar.dev
      - name: Deploy to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch --depth=1 origin gh-pages
          git checkout -b gh-pages
          git rm -rf .
          cp -r dist/portfolio/browser/* .
          cp sitemap.xml .
          cp robots.txt .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force --quiet

  release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
