name: Release Workflow

on:
  push:
    branches:
      - master

jobs:
  build-deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular Project
        run: ng build --base-href https://danieljancar.dev

      - name: Copy Sitemap and Robots
        run: |
          cp config/sitemap.xml dist/portfolio/browser
          cp config/robots.txt dist/portfolio/browser

      - name: Update Sitemap in Build Folder
        run: bash scripts/updateSitemap.sh dist/portfolio/browser/sitemap.xml dist/portfolio/browser/assets/blog/blog.json

      - name: Create CNAME
        run: bash scripts/createCNAME.sh

      - name: Configure Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions[bot]"

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/portfolio/browser --no-silent
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
