name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: ng build --base-href https://danieljancar.dev

      - name: Install angular-cli-ghpages
        run: npm install -g angular-cli-ghpages

      - name: Deploy to GitHub Pages
        run: ngh --dir=dist/portfolio/browser

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: master
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
