name: Release Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.set_output.outputs.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: set_output
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build -- --base-href https://danieljancar.dev

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.build.outputs.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: git fetch --depth=1 origin gh-pages
      - run: git checkout gh-pages
      - run: git rm -rf *
      - run: cp -r dist/portfolio/browser/* .
      - run: git add .
      - run: git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
      - run: git push origin gh-pages --force --quiet

  release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
