name: Triweekly Merge

on:
  schedule:
    # Run every third Monday at 1am UTC
    - cron: '0 1 1-31/21 * 1' 

jobs:
  merge-develop-to-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DAILY_PUSH }}
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Setup Git
        run: |
          git config --global user.name "gh-actions[bot]"
          git config --global user.email "actions@github.com"

      - name: Merge develop into master
        run: |
          git fetch --all
          git checkout master
          git merge origin/develop
          git push origin master
